### ISSUE TITLE
KAFKA REST /api/kafka-rest-proxy  CONNECTIVITY ERROR

### ISSUE THREAD

**Issue by teo-chenglim** [Landoop/kafka-topics-ui#144]
Hi,

I try to connect Landoop Kafka UI with open source kafka

```bash
# Start Zookeeper
chenglim@chenglim-GL503VM:/amaris/kafka/kafka_2.12-2.1.0$ ./bin/zookeeper-server-start.sh config/zookeeper.properties

# Start Kafka
chenglim@chenglim-GL503VM:/amaris/kafka/kafka_2.12-2.1.0$ ./bin/kafka-server-start.sh config/server.properties

# Start Kafka Connect
chenglim@chenglim-GL503VM:/amaris/kafka/kafka_2.12-2.1.0$ bin/connect-distributed.sh config/connect-distributed.properties

# docker landoop-kafka-ui
chenglim@chenglim-GL503VM:/amaris/kafka/kafka_2.12-2.1.0$ docker run --rm -it -p 8000:8000 -e "KAFKA_REST_PROXY_URL=http://127.0.0.0.1:8083" -e "PROXY_SKIP_VERIFY=true" -e "PROXY=true" --net=host landoop/kafka-topics-ui

# docker landoop-kafka-ui, with docker0 ip
chenglim@chenglim-GL503VM:/amaris/kafka/kafka_2.12-2.1.0$ docker run --rm -it -p 8000:8000 -e "KAFKA_REST_PROXY_URL=http://172.17.0.1:8083" -e "PROXY_SKIP_VERIFY=true" -e "PROXY=true" --net=host landoop/kafka-topics-ui

# # docker landoop-kafka-ui with normal ip
chenglim@chenglim-GL503VM:/amaris/kafka/kafka_2.12-2.1.0$ docker run --rm -it -p 8000:8000 -e "KAFKA_REST_PROXY_URL=http://192.168.1.38:8083" -e "PROXY_SKIP_VERIFY=true" -e "PROXY=true" --net=host landoop/kafka-topics-ui

```

all led to same result
KAFKA REST
/api/kafka-rest-proxy 
CONNECTIVITY ERROR

```bash
Kafka Connect error

[2019-02-12 09:17:19,047] INFO 127.0.0.1 - - [12/Feb/2019:01:17:18 +0000] "GET / HTTP/1.1" 200 91  114 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2019-02-12 09:17:19,099] ERROR Uncaught exception in REST call to /favicon.ico (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper:61)
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:274)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

```

```bash
Test inside container


chenglim@chenglim-GL503VM:/amaris/kafka/kafka_2.12-2.1.0$ docker ps
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS              PORTS               NAMES
68508841a198        landoop/kafka-topics-ui   "/run.sh"           10 seconds ago      Up 8 seconds                            vibrant_lederberg
chenglim@chenglim-GL503VM:/amaris/kafka/kafka_2.12-2.1.0$ docker exec -it 685 ash
/ # netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:60561           0.0.0.0:*               LISTEN      -
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:53109           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:35389           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:2049            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:43111           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      -
tcp        0      0 :::53227                :::*                    LISTEN      -
tcp        0      0 :::41259                :::*                    LISTEN      -
tcp        0      0 :::111                  :::*                    LISTEN      -
tcp        0      0 :::35953                :::*                    LISTEN      -
tcp        0      0 :::8083                 :::*                    LISTEN      -
tcp        0      0 :::10259                :::*                    LISTEN      -
tcp        0      0 :::45813                :::*                    LISTEN      -
tcp        0      0 :::22                   :::*                    LISTEN      -
tcp        0      0 ::1:631                 :::*                    LISTEN      -
tcp        0      0 :::40829                :::*                    LISTEN      -
tcp        0      0 :::45407                :::*                    LISTEN      -
tcp        0      0 :::8000                 :::*                    LISTEN      1/caddy
tcp        0      0 :::2049                 :::*                    LISTEN      -
tcp        0      0 :::9092                 :::*                    LISTEN      -
tcp        0      0 :::2181                 :::*                    LISTEN      -
tcp        0      0 :::36327                :::*                    LISTEN      -
/ # apk --no-cache add curl 
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/4) Installing nghttp2-libs (1.32.0-r0)
(2/4) Installing libssh2 (1.8.0-r3)
(3/4) Installing libcurl (7.61.1-r1)
(4/4) Installing curl (7.61.1-r1)
Executing busybox-1.28.4-r1.trigger
OK: 7 MiB in 19 packages
/ # netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:60561           0.0.0.0:*               LISTEN      -
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:53109           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:35389           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:2049            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:43111           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      -
tcp        0      0 :::53227                :::*                    LISTEN      -
tcp        0      0 :::41259                :::*                    LISTEN      -
tcp        0      0 :::111                  :::*                    LISTEN      -
tcp        0      0 :::35953                :::*                    LISTEN      -
tcp        0      0 :::8083                 :::*                    LISTEN      -
tcp        0      0 :::10259                :::*                    LISTEN      -
tcp        0      0 :::45813                :::*                    LISTEN      -
tcp        0      0 :::22                   :::*                    LISTEN      -
tcp        0      0 ::1:631                 :::*                    LISTEN      -
tcp        0      0 :::40829                :::*                    LISTEN      -
tcp        0      0 :::45407                :::*                    LISTEN      -
tcp        0      0 :::8000                 :::*                    LISTEN      1/caddy
tcp        0      0 :::2049                 :::*                    LISTEN      -
tcp        0      0 :::9092                 :::*                    LISTEN      -
tcp        0      0 :::2181                 :::*                    LISTEN      -
tcp        0      0 :::36327                :::*                    LISTEN      -
/ # curl localhost:8083
{"version":"2.1.0","commit":"809be928f1ae004e","kafka_cluster_id":"6OUVAtodQkCvXDDrcXOrvQ"}
```

**Comment by solarmicrobe** [comment]
From your report I don't see you've started the rest proxy then you are pointing KAFKA_REST_PROXY_URL at http://127.0.0.0.1:8083.  You need to have the rest proxy running first before starting this UI.

**Comment by teo-chenglim** [comment]
Issue resolved. Thanks.

**Comment by rajivchirania** [comment]
@teo-chenglim How did you fix these issue..
 I am getting something like these when i am trying to get the topics

[2020-01-21 16:35:42,092] ERROR Uncaught exception in REST call to /topics/test (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper:61)
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:250)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)

**Comment by manee2k6** [comment]
KAFKA REST /api/kafka-rest-proxy CONNECTIVITY ERROR is the similar issue i am facing.
My setup with docker docker swarm cluster for kafka cluster, kafka rest api-5.3.1 , kafka schema-registry-5.3.1 versions absolutely works fine in stage , as i realize 5.3.1  version no more exist in the repo, so changed it to 5.3.3 and try running the kafka rest api and kafka schema registry 5.3.3 version on both. Kakfa topic ui still throws connectivity error as reported before. Please suggest me the best here.

**Comment by manee2k6** [comment]
Tried this to as per your recommendation in another thread:
changing the KAFKA_REST_LISTENERS to http://0.0.0.0:8082 resolved the problem. However, for future readers, setting KAFKA_REST_LISTENERS to http://rest_proxy:8082 results in the rest_proxy failing to start up.
